name: Sorting algorithm visualizer
on: [push]
jobs:
  run-app-tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
      - uses: actions/checkout@v2
      - name: setup nodejs and npm 
      - uses: actions/setup-node@v2
      - with: 
          node-version: '14'
      - name: Install project dependencies
      - run: npm i 
      - name: Run tests
      - run: npm test
